; PlatformIO Project Configuration File
; E-IoT Platform — ESP32 Firmware

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.partitions = min_spiffs.csv

lib_deps =
    ArduinoJson @ ^7.0.4
    256dpi/MQTT @ ^2.5.1
    mobizt/FirebaseClient @ ^2.0.3
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
